---
- name: Ensure packages installed
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - i3
  - qt-config
  become: yes

- name: Deploy config dirs
  file:
    name: "{{ lookup('env', 'HOME') }}/{{ item }}"
    state: directory
  with_items:
  - .config/i3
  - .config/xfce4/terminal

- name: Deploy configs from template
  template:
    src: "{{ item.template }}"
    dest: "{{ lookup('env', 'HOME') }}/{{ item.dest }}"
  with_items:
  - template: i3_config.j2
    dest: .config/i3/config
  - template: terminalrc.j2
    dest: .config/xfce4/terminal/terminalrc
