---
- name: Ensure packages installed
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - i3
  - qt-config
  - volumeicon
  - /usr/bin/xlock
  become: yes

- name: Deploy config dirs
  file:
    name: "{{ lookup('env', 'HOME') }}/{{ item.dest | dirname }}"
    state: directory
  with_items: "{{ config_templates }}"

- name: Deploy configs from template
  template:
    src: "{{ item.template }}"
    dest: "{{ lookup('env', 'HOME') }}/{{ item.dest }}"
  with_items: "{{ config_templates }}"
  register: deployed_config

- name: Reload i3
  command: /bin/sh -c "killall i3status ; i3-msg restart"
  # FIXME: any nice way to make this run only when i3 changed,
  # while keeping the config_templates loop structure?
  when: deployed_config is changed
  ignore_errors: yes
